### PR TITLE
Rearrange wrapping of Warp filters

### LINKED ISSUE #211: `timing_wrapper()` should only record after request routing is successful
I had an insight while working on the CORS headers that our `warp::wrap_fn(timing_wrapper(...))` filters are currently placed in the wrong spot. Currently, they each wrap a filter chain that begins with `warp::path(...)`. This means that, depending on the request and order of or'd filters, one request may enter timing filters multiple times, as it runs each path filter and rejects immediately before finding the correct one.

To solve this, we should rearrange all filters similar to how #210 did, by constructing a filter stack starting with the method filter, adding the wrapping timing filter to the stack at the end, and then placing that filter stack inside `warp::path("...").and(...)`. I'll take care of this as a follow-up.

### PR DESCRIPTION
**Pull request by divergentdave**
This moves metrics and tracing wrapping filters so that they don't fire until `warp::path` filters have succeeded. The relevant part of filter composition is now handled in a common helper method.

This fixes #211.

There are two other small behavioral changes: `collect_jobs_endpoint` now includes a `warp::get()` in its filter stack, and it was missing a trace filter previously. The new helper method is already paying off :smile:

### CODE REVIEW

File: janus_server/src/aggregator.rs [hunk 1]
```diff
@@ -1757,68 +1796,66 @@ fn aggregator_filter<C: Clock>(
...
-
-    let aggregate_endpoint = warp::path("aggregate")
-        .and(warp::post())
+        .map(error_handler(&response_counter, "hpke_config"))
+        .with(
+            warp::cors()
+                .allow_any_origin()
+                .allow_method("GET")
+                .max_age(CORS_PREFLIGHT_CACHE_AGE),
+        );
```
Comment (tgeoghegan) [inline janus_server/src/aggregator.rs:1822]: Why not set up the error handler and the CORS headers in `compose_common_wrappers`?

**Review by tgeoghegan — CHANGES_REQUESTED** [review]
Good catch on the collect job endpoint!

**Review by tgeoghegan — APPROVED** [review]

**Review by BranLwyd — APPROVED** [review]
